"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
logger = ...
DEFAULT_REDIS_SETTINGS = ...
def settings(**kwargs):
    """
    Get config settings based on the defaults and the arguments passed

    Parameters
    ----------
    **kwargs
        Redis server arguments, the keyword is the setting, the value is the
        value.
        If the value is of type list, the setting will be  set multiple times
        once with each value.
        If the value is None, the setting will be removed from the default
        settings if it exists.

    Returns
    -------
    dict
        Dictionary containing redis server settings, with the key being the
        setting name.  The values are the settings.  If the value is a list
        the setting will be repeated with each specified value.
    """
    ...

def config_line(setting, value):
    """
    Generate a single configuration line based on the setting and value

    Parameters
    ----------
    setting : str
        The configuration setting

    value : str
        The value for the configuration setting

    Returns
    -------
    str
        The configuration line based on the setting and value
    """
    ...

def config(**kwargs):
    """
    Generate a redis configuration file based on the passed arguments

    Returns
    -------
    str
        Redis server configuration
    """
    ...

