"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def debug_info_list():
    """
    Return a list with the debug information
    :return:
    """
    ...

def debug_info():
    """
    Return a multi-line string with the debug information
    :return:
    """
    ...

def print_debug_info():
    """
    Display information about the redislite build, and redis-server on stdout.
    :return:
    """
    ...

if __name__ == '__main__':
    ...
